USE [tokichoi_new]
GO

/****** Object:  Table [dbo].[ZCOPTD]    Script Date: 2016/6/30 ¤U¤È 04:40:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZCOPTD](
	[TD001] [nvarchar](4) NOT NULL,
	[TD002] [nvarchar](12) NOT NULL,
	[TD003] [nvarchar](4) NOT NULL,
	[TD004] [nvarchar](40) NOT NULL,
	[TD0089] [int] NULL,
 CONSTRAINT [PK_ZCOPTD] PRIMARY KEY CLUSTERED 
(
	[TD001] ASC,
	[TD002] ASC,
	[TD003] ASC,
	[TD004] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO


